### PR TITLE
tuner: Enable tuner init msg on INFO logs

### PR DESCRIPTION
**Pull request by arunkarthik-akkart**
*Description of changes:*
Enable tuner initialization message to be displayed on all NCCL_DEBUG=INFO and display the logs as part of the default subsystem (INIT)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by rauteric — APPROVED** [review]

**Review by AmedeoSapio — APPROVED** [review]

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by sielicki** [comment]
Can you please remove the merge commit? If you didn't intend for that to happen, consider adopting the following git settings:

```
git config --global pull.ff only
git config --global pull.rebase true
```

LGTM otherwise.

**Review by bwbarrett — CHANGES_REQUESTED** [review]
Patch looks fine, but please properly rebase and force push.  PRs should not have merge commits in them.

**Comment by arunkarthik-akkart** [comment]
> Patch looks fine, but please properly rebase and force push. PRs should not have merge commits in them.

Thanks for the feedback, I have rebased it.

**Comment by arunkarthik-akkart** [comment]
> Can you please remove the merge commit? If you didn't intend for that to happen, consider adopting the following git settings:
> 
> ```
> git config --global pull.ff only
> git config --global pull.rebase true
> ```
> 
> LGTM otherwise.

Thanks. I have rebased the PR after removing the merge commit.

**Review by bwbarrett — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Pull request merged**
