### PR TITLE
prepare v1.11.1-aws

### PR DESCRIPTION
**Pull request by aws-nslick**
Related-PR: https://github.com/aws/aws-ofi-nccl/pull/676

tag: https://github.com/aws-nslick/nccl-net-ofi/releases/tag/v1.11.1-aws

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aws-nslick** [comment]
r2: taking relnote fix mentioned in #678

**Review by rajachan — APPROVED** [review]

**Review by bwbarrett — APPROVED** [review]

**Comment by aws-nslick** [comment]
r3: needed 83f563c / 0ff714b

**Comment by aws-nslick** [comment]
@a-szegel can you do a once-over of the commits represented in:

```
git log eb5844632232e78e169ef4872cb58c2d1ef6eb09..71d05d6f3976ec9c678b3628302bcf17b2e8acc4 -- .ci
```

That is,

```
git log $(git merge-base upstream/master aws-nslick/v1.11.x-aws)..$(git log -1 --format="%H" upstream/master) -- .ci
```

I want to make sure there's no essential jenkins CI params missing on this relatively old branch.

**Comment by aws-nslick** [comment]
Noting here that this was merged slightly in-advance of the pr-ci job finishing, and commenting here so that I can't forget to follow-up with a pass/fail result.

**Comment by aws-nslick** [comment]
Note: this PR produced a similar issue as described on the 1.12.1 pr: https://github.com/aws/aws-ofi-nccl/pull/678#issuecomment-2437074298

Also noting that despite that CI still shows orange, the run did complete successfully.

**Pull request merged**
