### PR TITLE
.ci/aws: Add aws-ofi-nccl functional tests to ci

### PR DESCRIPTION
**Pull request by a-szegel**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by AmedeoSapio** [comment]
bot:aws:retest

**Review by AmedeoSapio — APPROVED** [review]

**Comment by AmedeoSapio** [comment]
bot:aws:retest

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Pull request merged**
