### PR TITLE
.ci/aws: Add Jenkins p4d CI tests

### PR DESCRIPTION
**Pull request by a-szegel**
Add new AWS CI to aws-ofi-nccl repo.

### CODE REVIEW

**Comment by a-szegel** [comment]
Needed to restart Jenkins to add lockable resources.  aws:bot:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
Confirmed I can trigger new builds via the above string from an account that has write access

**Review by rajachan — APPROVED** [review]

**Review by rauteric — APPROVED** [review]

**Pull request merged**
