### PR TITLE
.ci/aws: Add p3dn testing to Jenkins

### PR DESCRIPTION
**Pull request by a-szegel**
Add p3dn testing to Jenkins.  This PR will not work until p3dn capacity arrives in the account.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-szegel** [comment]
Canceled the first build because capacity hasn't arrived yet.

**Comment by a-szegel** [comment]
meh, ran into another PF bug... fixing

**Comment by a-szegel** [comment]
This is waiting on 1 last internal pipeline deployment, then I will rebuild in ~1 hour.

**Review by rauteric — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
More bugs with how we are setting up cuda drivers for p3dn... fixing

**Comment by a-szegel** [comment]
bot:aws:retest. aws-ofiwg-bot is not authorized to re-trigger builds

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest .... p5 build got a bad node.

**Comment by a-szegel** [comment]
bot:aws:retest... one of the p3dn jobs failed because it was slow to free

**Comment by a-szegel** [comment]
bot:aws:retest

**Pull request merged**
