### PR TITLE
rdma: Use get_device_from_ep() accessor

### PR DESCRIPTION
**Pull request by bwbarrett**
Clean up the code to always use the get_device_from_ep() accessor function instead of poking through data structures.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by rauteric — APPROVED** [review]

**Review by aws-nslick — APPROVED** [review]

**Comment by aws-nslick** [comment]
aws:bot:retest

**Comment by rauteric** [comment]
bot:aws:retest?

**Comment by aws-nslick** [comment]
bot:aws:retest

**Comment by aws-nslick** [comment]
bot:aws:retest

**Pull request merged**
