### PR TITLE
Fix compile issue on centos and rhel7 platforms

### PR DESCRIPTION
**Pull request by rashikakheria**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nzmsv** [comment]
I believe we can just supply `-std=c++11` to `gcc` to make this work.  It wasn't the default in these older versions but the specific features have been around for a while (since 4.3).

**Comment by rashikakheria** [comment]
> I believe we can just supply `-std=c++11` to `gcc` to make this work. It wasn't the default in these older versions but the specific features have been around for a while (since 4.3).

I thought about that. I preferred to use the C keyword specifically since our code is C based. Do you see any issues with using the keyword directly?

**Comment by nzmsv** [comment]
The Static_assert keyword is a newer feature than the macro I believe.  It seems weird to mix old-school "all declarations up front" style with new features.  Maybe we can do both?  Switch to a newer standard flag, use a different static assert keyword, but keep the use of scoped declarations?

**Review by nzmsv — APPROVED** [review]

**Comment by rashikakheria** [comment]
The reason to move declaration of `page_size` at the top of function is to prevent calling unmap with un-initialized variable when `got unlock` is used.

**Pull request merged**
