### PR TITLE
[v1.10.x-aws] .ci/aws: Backport a bunch of CI changes to include region-less Jenkinsfile definitions

### PR DESCRIPTION
**Pull request by a-szegel**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-szegel** [comment]
updating v1.10.x to use GH runners instead of codebuild.

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by aws-nslick** [comment]
lgtm, but I resent that we are maintaining so many concurrent releases.

**Review by aws-nslick — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Pull request merged**
