### PR TITLE
.ci/aws: Unpin al2 p3dn ami

### PR DESCRIPTION
**Pull request by a-szegel**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-szegel** [comment]
bot:aws:retest

**Review by bwbarrett — CHANGES_REQUESTED** [review]
You need some why somewhere in here.

**Comment by a-szegel** [comment]
repushed and updated commit message

**Comment by a-szegel** [comment]
Do not merge until we figure out our issues with AMI building.

**Review by bwbarrett — APPROVED** [review]

**Pull request merged**
