### PR TITLE
.ci/aws: Decrease NCCL_TEST iterations to 5

### PR DESCRIPTION
**Pull request by a-szegel**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-szegel** [comment]
bot:aws:retest

**Review by rauteric — APPROVED** [review]

**Comment by sielicki** [comment]
What was it previously?

**Comment by sunkuamzn** [comment]
@sielicki it was 20

**Comment by a-szegel** [comment]
bot:aws:retest

**Review by bwbarrett — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Pull request merged**
